logging:
  level:
    com.zaxxer.hikari: debug
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: '${DB_USER}'
    password: '${DB_PASSWORD}'
    hikari:
      connection-timeout:  5000 # Default: 30000(30 sec)
      connection-test-query: SELECT now()
      maximum-pool-size: 10
